from daft import PGM

pgm = PGM(directed=True)

pgm.add_node('G', content='G', observed=False, x=0, y=0)
pgm.add_node('rho', content='rho', observed=False, x=1, y=0, alternate=True)
pgm.add_node('R', content='R', observed=True, x= .25+.75/2, y=1.2)
pgm.add_node('tau', content='tau', observed=True, x=1.5, y=.8)
pgm.add_node('f', content='f', observed=False, x=1.75, y=2, shape='rectangle')
pgm.add_node('beta', content='beta', observed=False, x=1.75, y=3, alternate=True)
pgm.add_node('ITI', content='ITI', observed=True, x=2.5, y=2)
pgm.add_node('k', content='k', observed=False, x=1, y=2, alternate=True)
pgm.add_node('B', content='B', observed=False, x=-0.5, y=2)
pgm.add_node('p_omega', content='Pom', observed=False, x=.25, y=3, alternate=True)
pgm.add_node('omega', content='om', observed=False, x=.25, y=2.25, shape='rectangle')
pgm.add_node('a', content='a', observed=False, x=-1.25, y=2.5)
pgm.add_node('bHat', content='b\'', observed=False, x=-2, y=3.2, alternate=True)
pgm.add_node('m', content='m', observed=False, x=-1.25, y=3.2, alternate=True)
pgm.add_node('xHat', content='x\'', observed=False, x=-.5, y=3.2, shape='rectangle')
pgm.add_node('x', content='x', observed=False, x=0, y=3.75)
pgm.add_node('sigma', content='sig_x', observed=False, x=-.9, y=3.95)
pgm.add_edge('sigma','xHat')
pgm.add_edge('a','B')
pgm.add_edge('x','B')
#TODO: add real boundary b
pgm.add_edge('bHat','a')
pgm.add_edge('m','a')
pgm.add_edge('xHat','a')
pgm.add_edge('x','xHat')
pgm.add_edge('p_omega','omega')
pgm.add_edge('omega','R')
pgm.add_edge('B','R')
pgm.add_edge('beta','f')
pgm.add_edge('f','R')
pgm.add_edge('f','tau')
pgm.add_edge('k','R')
pgm.add_edge('k','tau')
pgm.add_edge('ITI','tau')
pgm.add_edge('R','tau')
pgm.add_edge('R','G')
pgm.add_edge('tau','G')
pgm.add_edge('R','rho')
pgm.add_edge('tau','rho')

pgm.render()
pgm.figure.show()